apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-service
  namespace: jerry
  labels:
    app: agent-service
    component: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-service
  template:
    metadata:
      labels:
        app: agent-service
        component: agent
    spec:
      containers:
      - name: agent-service
        image: jerry/agent-service:latest
        ports:
        - containerPort: 8003
          name: http
        env:
        - name: MODEL_SERVICE_URL
          value: "http://model-service:8001"
        - name: RAG_SERVICE_URL
          value: "http://rag-service:8002"
        - name: AGENT_SERVER_HOST
          value: "0.0.0.0"
        - name: AGENT_SERVER_PORT
          value: "8003"
        - name: AGENT_MAX_ITERATIONS
          valueFrom:
            configMapKeyRef:
              name: jerry-config
              key: AGENT_MAX_ITERATIONS
        - name: CONVERSATION_MEMORY_SIZE
          valueFrom:
            configMapKeyRef:
              name: jerry-config
              key: CONVERSATION_MEMORY_SIZE
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 15
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
      securityContext:
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: agent-service
  namespace: jerry
  labels:
    app: agent-service
spec:
  selector:
    app: agent-service
  ports:
  - port: 8003
    targetPort: 8003
    name: http
  type: ClusterIP