openapi: 3.0.3
info:
  title: Jerry Agent Service API
  description: Internal API for Jerry's LangChain agent interactions
  version: 1.0.0
servers:
  - url: http://localhost:8003
    description: Local agent service

paths:
  /v1/chat:
    post:
      summary: Process conversation with agent
      operationId: processConversation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConversationRequest'
      responses:
        '200':
          description: Agent response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /v1/conversations/{conversation_id}/summary:
    post:
      summary: Generate conversation summary
      operationId: summarizeConversation
      parameters:
        - name: conversation_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Summary generated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SummaryResponse'

  /v1/health:
    get:
      summary: Health check
      operationId: healthCheck
      responses:
        '200':
          description: Service healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

components:
  schemas:
    ConversationRequest:
      type: object
      required:
        - user_id
        - message
        - conversation_id
      properties:
        user_id:
          type: string
        message:
          type: string
          minLength: 1
        conversation_id:
          type: string
          format: uuid
        channel_id:
          type: string
        use_rag:
          type: boolean
          default: true
        use_cache:
          type: boolean
          default: true
        context:
          type: object
          additionalProperties: true

    ConversationResponse:
      type: object
      required:
        - message
        - conversation_id
        - response_time_ms
      properties:
        message:
          type: string
        conversation_id:
          type: string
          format: uuid
        response_time_ms:
          type: number
        tokens_used:
          type: integer
        sources_used:
          type: array
          items:
            type: string
        tools_used:
          type: array
          items:
            type: string
        cached:
          type: boolean
        confidence_score:
          type: number
          minimum: 0.0
          maximum: 1.0

    SummaryResponse:
      type: object
      required:
        - summary
        - conversation_id
      properties:
        summary:
          type: string
        conversation_id:
          type: string
          format: uuid
        message_count:
          type: integer
        tokens_saved:
          type: integer

    HealthResponse:
      type: object
      required:
        - status
        - timestamp
      properties:
        status:
          type: string
          enum: [healthy, degraded, unhealthy]
        timestamp:
          type: string
          format: date-time
        agent_status:
          type: string
        active_conversations:
          type: integer
        cache_hit_rate:
          type: number

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: object
          required:
            - message
            - type
          properties:
            message:
              type: string
            type:
              type: string
            code:
              type: string